title: hainfx' Blog # The title of the blog
author: hainfx # Your name
email: hainfx@163.com # your email shown in the footer
url: https://hainfx.github.io # this is your site's root address.
description: > # this means to ignore newlines until "show_excerpts:"
  About me
favicon: "./favicon.ico" # set the favicon of the site
google_analytics: G-xxx

show_excerpts: false # set to true to show excerpts on the homepage
permalink: /:categories/:year/:title:output_ext

highlighter: none

beian: 备案号

timezone: Asia/Shanghai

# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  avatar_url: "./favicon.ico" # avatar in about page
  about_you: Live up this live.
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    # twitter:
    github: hainfx
    # rss: RSS
    # dribbble:
    # facebook: huangyz0918
    # flickr:
    # instagram:
    # linkedin: yizheng-huang
    # pinterest:
    # youtube:
    # youtube_channel:
    # youtube_channel_name:
    # telegram:
    # googleplus:
    # microdotblog:
    # reddit:
    # Mastodon instances
    # mastodon:
    # - username:
    #   instance:
    # - username:
    #   instance:

# Build settings
# theme: moving # note, please use huangyz0918/moving if you want to publish to Github Pages.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge